name: pyart-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - gdal
  - numpy
  - scipy
  - matplotlib
  - netcdf4
  - pytest
  - trmm_rsl
  - wradlib
  - cartopy
  - cvxopt
  - xarray
  - sphinx
  - ipython
  - pandoc
  - pip
  - pip:
      - sphinx_rtd_theme
      - sphinx_gallery
      - sphinx-copybutton
      - nbsphinx