on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, closed]

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: AV scan
    steps:
    - uses: actions/checkout@v3
    - name: Git AV Scan
      uses: djdefi/gitavscan@main
      with:
        full: '--full'
